name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: i686-pc-windows-msvc
        override: true
        
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --target i686-pc-windows-msvc
